language: python
jdk: openjdk9
python: 3.4
sudo: required
env:
  global:
    - TIMEOUT=1000
virtualenv:
  system_site_packages: true
addons:
  apt:
    update: true

before_install:
  - sudo apt-get update -qq
  - mvn -f src/ clean install
# install:
#   - .travis/install.sh
before_script:
  - export STARTDATETIME=$(date +"%Y-%m-%d %H:%M:%S")
#   - .travis/login.sh
script:
  # - .travis/travis_wait_log make configure_databricks test=true
  - echo "$STARTDATETIME"
  - java -jar src/integration-tests/target/integration-tests-1.0-SNAPSHOT-jar-with-dependencies.jar "$STARTDATETIME"